### ISSUE TITLE
[breeze widget style]: disabled animations will not allow moving panels and crash some apps like kdenlive while trying

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.13#36]
since Animations are disabled on Maui and Netrunner, this affects all out installs and a patch to fix this would be very welcomed.

**Comment by star-buck** [comment]
https://bugs.kde.org/show_bug.cgi?id=371667

**Comment by notmart** [comment]
just to confirm: the setting in maui is:

[Units]
longRuration=0

in the file called plasmarc?

**Comment by notmart** [comment]
with that setting i cannot reproduce the crash, must be some other setting

**Comment by notmart** [comment]
talked with leszek, seems to be a Qt bug already solved in 5.7.1

**Comment by star-buck** [comment]
Ah nice, lets wait for that then.

**Comment by notmart** [comment]
may be tried with the more recent qt releases that we ship nowdays
