### ISSUE TITLE
TM: some programs invoke two consecutive tasks

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.13#66]
e.g. System Settings:
https://www.dropbox.com/s/40aw11zrkycpwxb/TM-system-settings.mkv?dl=0

maybe its possible to obmit or only show one?

**Comment by eikehein** [comment]
This is most likely a bug in System Settings, will look into it.

**Comment by eikehein** [comment]
(It's not actually two tasks, it's the startup notification and the window, and the latter doesn't match the former because they don't match in app ids.)

**Comment by star-buck** [comment]
Do other apps solve this?
Or why is it a different id with SS?

**Comment by eikehein** [comment]
I'll update after I debugged that :)

**Comment by eikehein** [comment]
I'll update after I debugged that :)

**Comment by eikehein** [comment]
This was broken by 39e13de3468add20f37eb0f8814dd6996384d23f in systemsettings.git by a commit by mgraesslin.

System Settings installs two .desktop files:
- systemsettings.desktop with name System Settings shown in KDE
- kdesystemsettings.desktop with name "KDE System Settings" and NotShowIn=KDE

39e13de3 makes System Settings set its .desktop file to "kdesystemsettings". This .desktop file is put as a window hint on the window, which we dutifully follow, so for the window we use that .desktop file (even though it's not the right one for KDE - we follow what the app tells us to do). But the startup notification is built (somewhere in Qt and KStartupInfo) based on other app data, and based on the "systemsettings" name there we find the other .desktop file. App id, app name and launcher URL all don't match, so we can't determine the startup notification is for the same app as the window.

Solutions to solving this:
- Revert the IMHO completely wrong change in System Settings
- Ignore the .desktop file window hint (which would break other apps)
- Add even more complex code where we do follow the hint but then toss it aside if the .desktop file contents say NotShowIn=KDE
- Add a special mapping rule exception for our own control panel app (lol)

I might do the third one, even though I hate it. But knowing Martin I probably can't get 1 through.

**Comment by eikehein** [comment]
I wrote a mail to mgraesslin now, this will probably take a while (and thus until post-vacation) to sort out given the number of stakeholders involved. The two .desktop files thing is because of a name clash with Gnome btw.

**Comment by eikehein** [comment]
Another problem with doing (3) is that it would mean I/O in a hotpath (opening and parsing the .desktop file from the window hint to figure out if it's NotShowIn=KDE) which would be really bad for performance ... I really want System Settings fixed instead ideally.

**Comment by eikehein** [comment]
Thinking about it, IMHO the change in System Settings is _clearly_ 100% wrong: StartupInfo::applicationId is set from the .desktop file an app is started from, and systemsettings.desktop is the .desktop file that System Settings exposes to our menus. If it's then setting a different .desktop file for its windows, not being able to match it is correct libtm behavior. This really needs to be fixed in SS - I'll convince Martin of that somehow ...

**Comment by eikehein** [comment]
Patch https://phabricator.kde.org/D5006
